### ISSUE TITLE
Pinned version of Werkzeug in requirements needs to be updated to work with run_simple

### ISSUE THREAD

**Issue by SavSanta** [debugleader/Flask-Gym#1]
Kali Linux 2022.04 (ie Debian/Ubuntu derivative)

# Was getting the error about `run_simple() got an unexpected keyword argument 'exclude_patterns'`

# Werkzeug version 1.0.1 is in the requirements. Trying to run gave me

```
(kratos) ┌──(kali㉿kratos)-[~/Projects/kratos/kratos/Flask-Gym]
└─$ flask run                                                                                                             2 ⨯
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/kali/Projects/kratos/kratos/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/flask/cli.py", line 985, in main
    cli.main()
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/flask/cli.py", line 851, in run_command
    run_simple(
TypeError: run_simple() got an unexpected keyword argument 'exclude_patterns'

```

# Uninstalling the Werkzeug 1.0.1 versions

```
(kratos) ┌──(kali㉿kratos)-[~/Projects/kratos/kratos/Flask-Gym]
└─$ pip uninstall Werkzeug
Found existing installation: Werkzeug 1.0.1
Uninstalling Werkzeug-1.0.1:
  Would remove:
    /home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/Werkzeug-1.0.1.dist-info/*
    /home/kali/Projects/kratos/kratos/lib/python3.9/site-packages/werkzeug/*
Proceed (Y/n)? y
  Successfully uninstalled Werkzeug-1.0.1
```                                                                                                                              

# Installing the latest. I didnt test to see if maybe a slightly older version fixes it. Just updated to the current latest as of today from pip repos which is 2.1.1

```
(kratos) ┌──(kali㉿kratos)-[~/Projects/kratos/kratos/Flask-Gym]
└─$ pip install Werkzeug  
Collecting Werkzeug
  Using cached Werkzeug-2.1.1-py3-none-any.whl (224 kB)
Installing collected packages: Werkzeug
Successfully installed Werkzeug-2.1.1
```

# Run the program again and it works.
                                                                                                                              
```
(kratos) ┌──(kali㉿kratos)-[~/Projects/kratos/kratos/Flask-Gym]
└─$ flask run                                                                      
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)

```

**Comment by SavSanta** [comment]
Disregard. This is only when using Flask 2. Project was built for 1
